### ISSUE TITLE
No github tag for 1.8.0 & 1.8.1

### ISSUE THREAD

**Issue by jackturnbull** [spider-gazelle/active-model#15]
Meaning I'm unable to pull down the latest version with:

```yaml
  active-model:
    github: spider-gazelle/active-model
    version: ~> 1.8
```

```
Error resolving active-model (~> 1.8)
```
